name: SSH
on:
  workflow_dispatch:

jobs:
  secure-ssh:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    steps:
      - name: Switch to root user and configure environment
        run: |
          sudo -i <<EOF
          if ! id -u ubuntu >/dev/null 2>&1; then
            useradd -m -s /bin/bash ubuntu
            usermod -aG sudo ubuntu
          fi
          echo "ubuntu:@Awf123456789" | chpasswd
          echo "ubuntu ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/ubuntu-ssh
          chmod 0440 /etc/sudoers.d/ubuntu-ssh
          EOF

      - name: Configure SSH Service & allow all ports/protocols
        run: |
          sudo -i <<EOF
          sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          systemctl restart ssh
          ufw allow from any to any  # 允许所有端口所有协议
          ufw reload
          grep -E "PasswordAuthentication|PermitRootLogin" /etc/ssh/sshd_config
          systemctl status ssh --no-pager
          ufw status  # 验证所有端口协议放行状态
          EOF

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sudo sh
          sudo apt clean

      - name: Connect to Tailscale
        env:
          TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
        run: |
          sudo tailscale up --authkey "$TAILSCALE_AUTH_KEY" --hostname "github-ssh-${{ github.run_id }}"
          TAILSCALE_IP=""
          RETRIES=0
          while [ -z "$TAILSCALE_IP" ] && [ $RETRIES -lt 10 ]; do
            TAILSCALE_IP=$(sudo tailscale ip -4)
            sleep 3
            RETRIES=$((RETRIES + 1))
          done
          if [ -z "$TAILSCALE_IP" ]; then
            echo "Error: Failed to get Tailscale IPv4 address."
            exit 1
          fi
          echo "TAILSCALE_IP=$TAILSCALE_IP" >> $GITHUB_ENV
          echo "SSH_USER=ubuntu" >> $GITHUB_ENV
          echo "SSH_PASSWORD=@Awf123456789" >> $GITHUB_ENV

      - name: Verify SSH Connection
        run: |
          echo "Verifying SSH connectivity to ${{ env.TAILSCALE_IP }}:22..."
          if ! nc -z ${{ env.TAILSCALE_IP }} 22; then
            echo "Error: SSH Port 22 is not reachable on ${{ env.TAILSCALE_IP }}."
            exit 1
          fi

      - name: Show SSH Info & Keep Alive
        run: |
          echo "======================================"
          echo "SSH Remote Connection Info"
          echo "======================================"
          echo "Tailscale Private IP: ${{ env.TAILSCALE_IP }}"
          echo "Username: ${{ env.SSH_USER }}"
          echo "Password: ${{ env.SSH_PASSWORD }}"
          echo "Connect Command: ssh ${{ env.SSH_USER }}@${{ env.TAILSCALE_IP }}"
          echo "======================================"
          while true; do
            echo "SSH Service running... Current Time: $(date '+%Y-%m-%d %H:%M:%S')"
            sleep 300
          done
