name: SSH
on: workflow_dispatch
jobs:
  secure-ssh:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    steps:
      - name: Check Port 22 Occupation
        run: |
          OCCUPIED=$(sudo lsof -i:22 | grep -v "sshd")
          if [ -n "$OCCUPIED" ]; then
            echo "Error: Port 22 is occupied by other processes!"
            exit 1
          fi

      - name: Configure SSH Service
        run: |
          sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo systemctl restart ssh
          sudo ufw allow 22/tcp
          sudo ufw reload
          grep -E "PasswordAuthentication|PermitRootLogin" /etc/ssh/sshd_config
          systemctl status ssh
          ufw status

      - name: Set Random Root Password
        run: |
          RANDOM_PASSWORD=$(openssl rand -base64 12 | sed 's/[\/+=]/X/g' | head -c 16)
          echo "root:$RANDOM_PASSWORD" | sudo chpasswd
          echo "SSH_PASSWORD=$RANDOM_PASSWORD" >> $GITHUB_ENV
          echo "SSH_USER=root" >> $GITHUB_ENV

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo apt clean

      - name: Connect to Tailscale
        env:
          TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
        run: |
          sudo tailscale up --authkey "$TAILSCALE_AUTH_KEY" --hostname "github-ssh-${{ github.run_id }}"
          TAILSCALE_IP=$(sudo tailscale ip -4)
          echo "TAILSCALE_IP=$TAILSCALE_IP" >> $GITHUB_ENV

      - name: Verify SSH Connection
        run: |
          echo "Tailscale Private IP: ${{ env.TAILSCALE_IP }}"
          if ! nc -z ${{ env.TAILSCALE_IP }} 22; then
            echo "Error: SSH Port 22 is not reachable!"
            exit 1
          fi
          echo "SSH Service is ready for connection."

      - name: Show SSH Connection Info & Keep Alive
        run: |
          echo "======================================"
          echo "SSH Remote Connection Info"
          echo "======================================"
          echo "Tailscale Private IP: ${{ env.TAILSCALE_IP }}"
          echo "Username: ${{ env.SSH_USER }}"
          echo "Password: ${{ env.SSH_PASSWORD }}"
          echo "Connect Command: ssh ${{ env.SSH_USER }}@${{ env.TAILSCALE_IP }}"
          echo "======================================"
          while true; do
            echo "SSH Service is running... $(date)"
            sleep 300
          done
